apiVersion: v1
description: 'KubeVault Operator by AppsCode - HashiCorp Vault Operator for Kubernetes'
name: kubevault
version: v0.4.0-beta.0
appVersion: v0.4.0-beta.0
home: https://kubevault.com
icon: https://cdn.appscode.com/images/products/kubevault/icons/android-icon-192x192.png
sources:
- https://github.com/kubevault
maintainers:
- name: appscode
  email: support@appscode.com
