apiVersion: catalog.kubevault.com/v1alpha1
kind: VaultServerVersion
metadata:
  name: "1.2.3"
  labels:
    {{- include "kubevault-catalog.labels" . | nindent 4 }}
spec:
  version: "1.2.3"
  vault:
    image: "vault:1.2.3"
  unsealer:
    image: "{{ .Values.image.registry }}/vault-unsealer:v0.3.0"
  exporter:
    image: "{{ .Values.image.registry }}/vault-exporter-linux-amd64:v0.3.0"
