apiVersion: v2
name: kubevault-metrics
description: KubeVault State Metrics
type: application
version: v2026.1.8-rc.0
appVersion: v2026.1.8-rc.0
home: https://kubevault.com
icon: https://cdn.appscode.com/images/products/kubevault/kubevault-community-icon.png
sources:
- https://github.com/kubevault
maintainers:
- name: appscode
  email: support@appscode.com
