apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plans.products.x-helm.dev
spec:
  group: products.x-helm.dev
  names:
    kind: Plan
    listKind: PlanList
    plural: plans
    singular: plan
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              aggregateUsage:
                type: string
              amount:
                format: int64
                type: integer
              amountDecimal:
                format: double
                type: number
              billingScheme:
                type: string
              bundle:
                properties:
                  name:
                    type: string
                  sourceRef:
                    properties:
                      apiGroup:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - name
                    type: object
                required:
                - name
                - sourceRef
                type: object
              currency:
                type: string
              description:
                type: string
              displayName:
                type: string
              id:
                type: string
              includedPlans:
                items:
                  type: string
                type: array
              interval:
                type: string
              intervalCount:
                format: int64
                type: integer
              name:
                type: string
              phase:
                type: string
              pricingPattern:
                additionalProperties:
                  properties:
                    expression:
                      type: string
                    sizedPrices:
                      items:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          price:
                            format: double
                            type: number
                        required:
                        - cpu
                        - memory
                        - price
                        type: object
                      type: array
                  type: object
                type: object
              productID:
                type: string
              tiers:
                items:
                  properties:
                    flatAmount:
                      format: int64
                      type: integer
                    flatAmountDecimal:
                      format: double
                      type: number
                    unitAmount:
                      format: int64
                      type: integer
                    unitAmountDecimal:
                      format: double
                      type: number
                    upTo:
                      format: int64
                      type: integer
                  type: object
                type: array
              tiersMode:
                type: string
              transformUsage:
                properties:
                  divideBy:
                    format: int64
                    type: integer
                  round:
                    type: string
                type: object
              trialPeriodDays:
                format: int64
                type: integer
              usageType:
                type: string
              weight:
                format: int32
                type: integer
            required:
            - description
            - displayName
            - id
            - name
            - phase
            - productID
            - weight
            type: object
          status:
            properties:
              observedGeneration:
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
